use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Represents a plan generated by the planner.
/// 
/// A plan consists of a sequence of steps that the executor will run
/// to accomplish a user's goal, along with reasoning about why this
/// plan was chosen.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Plan {
    /// The sequence of steps to execute
    pub steps: Vec<Step>,
    /// Reasoning or justification for this plan
    pub reasoning: String,
}

impl Plan {
    /// Creates a new plan with the given steps and reasoning.
    pub fn new(steps: Vec<Step>, reasoning: String) -> Self {
        Self { steps, reasoning }
    }
}

/// Represents a single step in a plan.
/// 
/// Steps can be tool calls, reasoning steps, or response generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Step {
    /// A call to an external tool
    ToolCall(ToolCall),
    /// An intermediate reasoning step
    Reasoning { text: String },
    /// A response to be returned to the user
    Response { text: String },
}

/// Represents a call to a specific tool with parameters.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    /// The name of the tool to invoke
    pub tool_name: String,
    /// The parameters to pass to the tool (as JSON)
    pub parameters: Value,
}

impl ToolCall {
    /// Creates a new tool call.
    pub fn new(tool_name: String, parameters: Value) -> Self {
        Self {
            tool_name,
            parameters,
        }
    }
}
