//! Executor crate for the AI Agent Framework
//!
//! This crate provides the execution system that runs plans generated by the planner.
//! The executor takes a plan with a sequence of steps and executes them in order,
//! managing tool invocations and storing results in memory for context.
//!
//! # Core Concepts
//!
//! - **Executor**: The main component that executes plans step by step
//! - **ExecutionResult**: The outcome of executing a complete plan
//! - **StepResult**: The result of executing a single step
//!
//! # Example
//!
//! ```rust,no_run
//! use executor::{Executor, ExecutionResult};
//! use tools::ToolRegistry;
//! use memory::InMemoryStore;
//! use planner::Plan;
//!
//! # async fn example() -> agent_core::Result<()> {
//! let registry = ToolRegistry::new();
//! let memory = Box::new(InMemoryStore::new());
//! let mut executor = Executor::new(registry, memory);
//!
//! // Execute a plan
//! let plan = Plan::new(vec![], "Example plan".to_string());
//! let result = executor.execute_plan(plan).await?;
//!
//! if result.success {
//!     println!("Plan executed successfully: {}", result.final_response);
//! }
//! # Ok(())
//! # }
//! ```

mod executor;
mod types;

// Re-export public types
pub use executor::Executor;
pub use types::{ExecutionResult, StepResult};
